"""Short, localized marketing copy for the generated home pages.

The longer descriptions and article content remain in content.py.
"""
HOME_UI = {
    "en": dict(
        nav=("How it works", "Languages", "Questions"), get="Get the app",
        eyebrow="A little companion for paper books", title=("Stay in", "the", "story."),
        lead="A new word shouldn’t take you out of a good book. Point your iPhone at the page, find its meaning, and keep reading.",
        download="Download on the", see="See how it works", price="One-time purchase. No subscription.",
        photo="Less searching. More reading.", photo_caption="The dictionary, right there on the page.",
        strip="A world of words", how_kicker="A moment of curiosity", how_title=("One word.", "A little more", "understanding."),
        how_lead="No typing. No switching between apps. Just a quick glance, then back to your book.",
        steps=[("Open your book. Open the app.", "Choose your book’s language and tap Start reading. You’re ready for the next unfamiliar word."),
               ("Point to a word.", "Hold the small green ring over the word for about a second. A highlight shows it’s been read."),
               ("Find the meaning. Read on.", "Read the definition, then swipe it away. Your camera is ready when curiosity strikes again.")],
        language_kicker="Choose the language of your book", language_title="Six languages.",
        language_lead="English is ready when you are. Download the other dictionaries you’d like to read with.",
        built_in="Built in", download_pack="Download", translation="Reading in English? Add optional word translations into any of the other five languages.",
        pack_note="All dictionaries and available translation packs are included in your purchase. Installed packs work offline.",
        screen_caption="Book language, in the app.", full_screen="View full screenshot ↗",
        quiet_kicker="A quieter kind of app", quiet_title=("Your book.", "Your moment.", "Yours to keep."),
        benefits=[("Take it off the grid.", "Installed dictionaries and translation packs work offline, whether you’re on a train or in your favourite reading corner."),
                  ("Keep your reading to yourself.", "Camera images and recognised words stay on your iPhone. No account, advertising, analytics or tracking."),
                  ("Buy once. Keep reading.", "All six dictionaries and available translation packs are included. No subscription or in-app purchases.")],
        questions_kicker="Before you turn the page", questions_title=("A few good", "questions."), support="Need a hand? Get in touch",
        faqs=[("Does Booktionary work offline?", "Yes. English definitions are built in. Download any additional dictionaries or translation packs while you’re online; once installed, they work without a connection. Checking the language catalog also needs internet access."),
              ("Which languages can I read?", "English, French, Spanish, Portuguese, Italian and German. Choose the language of your book before you start reading. English definitions are included in the app; the other five dictionaries download separately."),
              ("Can it translate words, too?", "When reading English books, you can add translations into French, Spanish, Portuguese, Italian or German. Download your chosen translation pack first. Coverage varies by word. Books in the other five languages show dictionary definitions, without translation."),
              ("Will it work with my iPhone?", "Booktionary requires an iPhone running iOS 17 or later. Good light and a clear printed page help the camera recognise words."),
              ("Do you collect my reading data?", "No. Camera images, recognised words and lookups stay on your device. There are no accounts, ads or analytics. Dictionary downloads contact the content host, which can receive connection details such as your IP address.")],
        final_kicker="For the love of paper books", final_title=("There’s a good book", "waiting for you."),
        requirements="For iPhone · iOS 17 or later", footer_line="A little more meaning in every page.",
        privacy="Privacy", licences="Licences", credit="Dictionary data from Wiktionary. Made for curious readers.", site_languages="Site language", related="Explore more reading questions",
    ),
    "fr": dict(
        nav=("Comment ça marche", "Langues", "Questions"), get="Obtenir l’app",
        eyebrow="Un compagnon pour les livres papier", title=("Restez dans", "votre", "histoire."),
        lead="Un mot inconnu ne devrait pas vous faire quitter un bon livre. Visez la page avec votre iPhone, trouvez le sens et reprenez votre lecture.",
        download="Télécharger sur l’", see="Voir comment ça marche", price="Achat unique. Sans abonnement.",
        photo="Moins de recherches. Plus de lecture.", photo_caption="Le dictionnaire, sur la page.",
        strip="Un monde de mots", how_kicker="Un instant de curiosité", how_title=("Un mot.", "Un peu plus de", "sens."),
        how_lead="Sans taper ni changer d’application. Un coup d’œil, puis retour au livre.",
        steps=[("Ouvrez le livre et l’app.", "Choisissez la langue du livre et touchez Commencer la lecture."),
               ("Visez un mot.", "Placez le petit cercle vert sur le mot pendant environ une seconde. Un surlignage confirme la lecture."),
               ("Découvrez le sens. Continuez.", "Lisez la définition, puis faites-la glisser. L’appareil photo reste prêt pour le mot suivant.")],
        language_kicker="Choisissez la langue du livre", language_title="Six langues.",
        language_lead="L’anglais est prêt à l’emploi. Téléchargez les autres dictionnaires selon vos lectures.",
        built_in="Intégré", download_pack="À télécharger", translation="Vous lisez en anglais ? Ajoutez des traductions facultatives vers l’une des cinq autres langues.",
        pack_note="Tous les dictionnaires et les packs de traduction disponibles sont compris dans l’achat. Les packs installés fonctionnent hors ligne.",
        screen_caption="Choix de la langue du livre dans l’app.", full_screen="Voir la capture complète ↗",
        quiet_kicker="Une app discrète", quiet_title=("Votre livre.", "Votre moment.", "Rien qu’à vous."),
        benefits=[("Lisez hors réseau.", "Les dictionnaires et traductions installés fonctionnent sans connexion."),
                  ("Gardez votre lecture privée.", "Les images et les mots reconnus restent sur votre iPhone. Sans compte, publicité, statistique ni suivi."),
                  ("Achetez une fois.", "Les six dictionnaires et les traductions disponibles sont compris. Sans abonnement ni achat intégré.")],
        questions_kicker="Avant de tourner la page", questions_title=("Quelques bonnes", "questions."), support="Besoin d’aide ? Écrivez-nous",
        faqs=[("Booktionary fonctionne-t-il hors ligne ?", "Oui. Le dictionnaire anglais est intégré. Téléchargez les autres dictionnaires et traductions avec une connexion ; une fois installés, ils fonctionnent hors ligne. La consultation du catalogue nécessite Internet."),
              ("Quelles langues puis-je lire ?", "L’anglais, le français, l’espagnol, le portugais, l’italien et l’allemand. Choisissez la langue du livre avant de commencer. L’anglais est intégré ; les cinq autres dictionnaires se téléchargent séparément."),
              ("L’app traduit-elle aussi les mots ?", "Pour les livres anglais, ajoutez des traductions vers le français, l’espagnol, le portugais, l’italien ou l’allemand. Téléchargez le pack voulu. La couverture varie selon le mot. Les cinq autres langues proposent des définitions, sans traduction."),
              ("Mon iPhone est-il compatible ?", "Booktionary nécessite un iPhone sous iOS 17 ou une version ultérieure. Un bon éclairage aide à reconnaître le texte."),
              ("Mes données de lecture sont-elles collectées ?", "Non. Les images, les mots reconnus et les recherches restent sur votre appareil. Sans compte, publicité ni statistiques. Le téléchargement des packs contacte l’hébergeur, qui peut recevoir votre adresse IP.")],
        final_kicker="Pour l’amour des livres papier", final_title=("Un bon livre", "vous attend."),
        requirements="Pour iPhone · iOS 17 ou version ultérieure", footer_line="Un peu plus de sens à chaque page.",
        privacy="Confidentialité", licences="Licences", credit="Données lexicales issues de Wiktionary. Pour les lecteurs curieux.", site_languages="Langue du site", related="Autres questions de lecture",
    ),
}

# Locale variants share the same editorial layout. Their existing long-form
# descriptions and support information remain available in content.py.
HOME_UI["fr-CA"] = {**HOME_UI["fr"], "price": "Achat unique. Sans abonnement.", "language_lead": "L’anglais est prêt à l’emploi. Téléchargez les autres dictionnaires selon vos lectures."}
HOME_UI["es"] = dict(
    nav=("Cómo funciona", "Idiomas", "Preguntas"), get="Descargar la app",
    eyebrow="Un pequeño compañero para los libros de papel", title=("Sigue dentro", "de la", "historia."),
    lead="Una palabra nueva no debería sacarte de un buen libro. Apunta a la página con tu iPhone, descubre su significado y sigue leyendo.",
    download="Descargar en el", see="Descubre cómo funciona", price="Compra única. Sin suscripción.",
    photo="Menos búsquedas. Más lectura.", photo_caption="El diccionario, en la misma página.", strip="Un mundo de palabras",
    how_kicker="Un momento de curiosidad", how_title=("Una palabra.", "Un poco más de", "comprensión."),
    how_lead="Sin escribir ni cambiar de app. Una mirada rápida y vuelta al libro.",
    steps=[("Abre el libro y la app.", "Elige el idioma del libro y toca Empezar a leer."),
           ("Apunta a una palabra.", "Coloca el pequeño círculo verde sobre la palabra durante un segundo. El resaltado confirma la lectura."),
           ("Encuentra el significado.", "Lee la definición y deslízala para cerrarla. La cámara queda lista para otra palabra.")],
    language_kicker="Elige el idioma del libro", language_title="Seis idiomas.",
    language_lead="El inglés está listo para usar. Descarga los demás diccionarios que necesites.",
    built_in="Incluido", download_pack="Descargar", translation="¿Lees en inglés? Añade traducciones opcionales a cualquiera de los otros cinco idiomas.",
    pack_note="Todos los diccionarios y paquetes de traducción disponibles están incluidos en la compra. Los instalados funcionan sin conexión.",
    screen_caption="Selección del idioma del libro en la app.", full_screen="Ver captura completa ↗",
    quiet_kicker="Una app más tranquila", quiet_title=("Tu libro.", "Tu momento.", "Solo tuyos."),
    benefits=[("Lee sin conexión.", "Los diccionarios y traducciones instalados funcionan sin internet."),
              ("Tu lectura es privada.", "Las imágenes y palabras reconocidas permanecen en tu iPhone. Sin cuenta, publicidad, analíticas ni seguimiento."),
              ("Compra una vez.", "Los seis diccionarios y las traducciones disponibles están incluidos. Sin suscripciones ni compras integradas.")],
    questions_kicker="Antes de pasar la página", questions_title=("Algunas buenas", "preguntas."), support="¿Necesitas ayuda? Escríbenos",
    faqs=[("¿Funciona sin conexión?", "Sí. El diccionario inglés está incluido. Descarga los demás diccionarios y traducciones con conexión; después funcionan sin internet. Consultar el catálogo requiere conexión."),
          ("¿Qué idiomas puedo leer?", "Inglés, francés, español, portugués, italiano y alemán. Elige el idioma del libro antes de leer. El inglés está incluido; los otros cinco diccionarios se descargan aparte."),
          ("¿También traduce palabras?", "Para libros en inglés puedes añadir traducciones al francés, español, portugués, italiano o alemán. Descarga primero el paquete elegido. La cobertura varía según la palabra. Los otros idiomas muestran definiciones, sin traducción."),
          ("¿Es compatible con mi iPhone?", "Booktionary necesita un iPhone con iOS 17 o posterior. Una buena iluminación facilita el reconocimiento."),
          ("¿Recopila mis datos de lectura?", "No. Las imágenes, palabras y búsquedas permanecen en tu dispositivo. Sin cuentas, anuncios ni analíticas. Las descargas contactan con el servidor, que puede recibir tu dirección IP.")],
    final_kicker="Por amor a los libros de papel", final_title=("Te espera", "un buen libro."), requirements="Para iPhone · iOS 17 o posterior",
    footer_line="Un poco más de significado en cada página.", privacy="Privacidad", licences="Licencias", credit="Datos léxicos de Wiktionary. Para lectores curiosos.", site_languages="Idioma del sitio", related="Más preguntas sobre la lectura",
)
HOME_UI["pt-BR"] = dict(
    nav=("Como funciona", "Idiomas", "Perguntas"), get="Baixar o app",
    eyebrow="Uma companhia para os livros de papel", title=("Fique dentro", "da", "história."),
    lead="Uma palavra nova não deveria interromper um bom livro. Aponte o iPhone para a página, descubra o significado e continue lendo.",
    download="Baixar na", see="Veja como funciona", price="Compra única. Sem assinatura.",
    photo="Menos buscas. Mais leitura.", photo_caption="O dicionário bem ali, na página.", strip="Um mundo de palavras",
    how_kicker="Um momento de curiosidade", how_title=("Uma palavra.", "Um pouco mais de", "sentido."),
    how_lead="Sem digitar ou trocar de app. Uma olhada rápida e de volta ao livro.",
    steps=[("Abra o livro e o app.", "Escolha o idioma do livro e toque em Começar a ler."),
           ("Aponte para uma palavra.", "Posicione o pequeno círculo verde sobre a palavra por cerca de um segundo. O destaque confirma a leitura."),
           ("Descubra o significado.", "Leia a definição e deslize para fechá-la. A câmera fica pronta para a próxima palavra.")],
    language_kicker="Escolha o idioma do livro", language_title="Seis idiomas.",
    language_lead="O inglês já está disponível. Baixe os outros dicionários que quiser usar.",
    built_in="Incluído", download_pack="Baixar", translation="Lendo em inglês? Adicione traduções opcionais para qualquer um dos outros cinco idiomas.",
    pack_note="Todos os dicionários e pacotes de tradução disponíveis estão incluídos na compra. Os instalados funcionam offline.",
    screen_caption="Idioma do livro no app.", full_screen="Ver captura completa ↗",
    quiet_kicker="Um app mais discreto", quiet_title=("Seu livro.", "Seu momento.", "Só seus."),
    benefits=[("Leia sem conexão.", "Dicionários e traduções instalados funcionam offline."),
              ("Sua leitura é particular.", "Imagens e palavras reconhecidas ficam no iPhone. Sem conta, anúncios, análises ou rastreamento."),
              ("Compre uma vez.", "Os seis dicionários e traduções disponíveis estão incluídos. Sem assinatura ou compras no app.")],
    questions_kicker="Antes de virar a página", questions_title=("Algumas boas", "perguntas."), support="Precisa de ajuda? Fale conosco",
    faqs=[("Funciona offline?", "Sim. O dicionário inglês já vem no app. Baixe outros dicionários e traduções enquanto estiver conectado; depois, eles funcionam offline. Consultar o catálogo requer internet."),
          ("Quais idiomas posso ler?", "Inglês, francês, espanhol, português, italiano e alemão. Escolha o idioma do livro antes de começar. O inglês está incluído; os outros cinco dicionários são baixados separadamente."),
          ("Também traduz palavras?", "Para livros em inglês, você pode adicionar traduções para francês, espanhol, português, italiano ou alemão. Baixe o pacote desejado. A cobertura varia conforme a palavra. Nos outros idiomas, há definições sem tradução."),
          ("Funciona no meu iPhone?", "Booktionary requer iPhone com iOS 17 ou posterior. Boa iluminação facilita o reconhecimento de texto."),
          ("Meus dados de leitura são coletados?", "Não. Imagens, palavras e consultas permanecem no aparelho. Sem conta, anúncios ou análises. Downloads acessam o servidor, que pode receber seu endereço IP.")],
    final_kicker="Para quem ama livros de papel", final_title=("Um bom livro", "espera por você."), requirements="Para iPhone · iOS 17 ou posterior",
    footer_line="Um pouco mais de sentido em cada página.", privacy="Privacidade", licences="Licenças", credit="Dados lexicais do Wiktionary. Para leitores curiosos.", site_languages="Idioma do site", related="Mais perguntas sobre leitura",
)
HOME_UI["pt-PT"] = {**HOME_UI["pt-BR"],
    "nav": ("Como funciona", "Línguas", "Perguntas"), "get": "Obter a aplicação", "eyebrow": "Uma companhia para livros em papel",
    "lead": "Uma palavra nova não devia interromper um bom livro. Aponte o iPhone à página, descubra o significado e continue a ler.",
    "download": "Descarregar na", "price": "Compra única. Sem subscrição.", "language_kicker": "Escolha a língua do livro",
    "language_title": "Seis línguas.", "language_lead": "O inglês já está disponível. Descarregue os outros dicionários que quiser usar.",
    "download_pack": "Descarregar", "translation": "A ler em inglês? Adicione traduções opcionais para qualquer uma das outras cinco línguas.",
    "pack_note": "Todos os dicionários e pacotes de tradução disponíveis estão incluídos na compra. Os instalados funcionam sem ligação.",
    "benefits": [("Leia sem ligação.", "Os dicionários e traduções instalados funcionam sem internet."),
                 ("A sua leitura é privada.", "As imagens e palavras reconhecidas ficam no iPhone. Sem conta, publicidade, análise ou rastreio."),
                 ("Compre uma vez.", "Os seis dicionários e traduções disponíveis estão incluídos. Sem subscrição nem compras integradas.")],
    "requirements": "Para iPhone · iOS 17 ou posterior", "privacy": "Privacidade", "site_languages": "Língua do site",
}
HOME_UI["it"] = dict(
    nav=("Come funziona", "Lingue", "Domande"), get="Scarica l’app",
    eyebrow="Un piccolo compagno per i libri di carta", title=("Resta dentro", "la", "storia."),
    lead="Una parola nuova non dovrebbe interrompere un bel libro. Inquadra la pagina con l’iPhone, scopri il significato e continua a leggere.",
    download="Scarica su", see="Scopri come funziona", price="Acquisto unico. Nessun abbonamento.",
    photo="Meno ricerche. Più lettura.", photo_caption="Il dizionario, proprio sulla pagina.", strip="Un mondo di parole",
    how_kicker="Un momento di curiosità", how_title=("Una parola.", "Un po’ più di", "significato."),
    how_lead="Niente da digitare, nessun cambio di app. Un’occhiata e torni al libro.",
    steps=[("Apri il libro e l’app.", "Scegli la lingua del libro e tocca Inizia a leggere."),
           ("Inquadra una parola.", "Tieni il piccolo cerchio verde sulla parola per circa un secondo. L’evidenziazione conferma la lettura."),
           ("Trova il significato.", "Leggi la definizione e scorri per chiuderla. La fotocamera resta pronta per la prossima parola.")],
    language_kicker="Scegli la lingua del libro", language_title="Sei lingue.",
    language_lead="L’inglese è già pronto. Scarica gli altri dizionari che vuoi usare.",
    built_in="Incluso", download_pack="Scarica", translation="Leggi in inglese? Aggiungi traduzioni facoltative verso una delle altre cinque lingue.",
    pack_note="Tutti i dizionari e i pacchetti di traduzione disponibili sono inclusi nell’acquisto. Quelli installati funzionano offline.",
    screen_caption="Lingua del libro nell’app.", full_screen="Vedi lo screenshot completo ↗",
    quiet_kicker="Un’app più discreta", quiet_title=("Il tuo libro.", "Il tuo momento.", "Solo tuoi."),
    benefits=[("Leggi offline.", "I dizionari e le traduzioni installati funzionano senza connessione."),
              ("La lettura resta privata.", "Immagini e parole riconosciute restano sull’iPhone. Niente account, pubblicità, statistiche o tracciamento."),
              ("Acquista una volta.", "I sei dizionari e le traduzioni disponibili sono inclusi. Nessun abbonamento o acquisto in-app.")],
    questions_kicker="Prima di voltare pagina", questions_title=("Qualche buona", "domanda."), support="Hai bisogno di aiuto? Scrivici",
    faqs=[("Funziona offline?", "Sì. Il dizionario inglese è incluso. Scarica gli altri dizionari e traduzioni quando sei online; poi funzionano senza connessione. Consultare il catalogo richiede Internet."),
          ("Quali lingue posso leggere?", "Inglese, francese, spagnolo, portoghese, italiano e tedesco. Scegli la lingua del libro prima di iniziare. L’inglese è incluso; gli altri cinque dizionari si scaricano separatamente."),
          ("Traduce anche le parole?", "Per i libri in inglese puoi aggiungere traduzioni in francese, spagnolo, portoghese, italiano o tedesco. Scarica il pacchetto desiderato. La copertura varia da parola a parola. Le altre lingue offrono definizioni, senza traduzione."),
          ("Funziona sul mio iPhone?", "Booktionary richiede un iPhone con iOS 17 o successivo. Una buona luce facilita il riconoscimento del testo."),
          ("Raccogliete i miei dati di lettura?", "No. Immagini, parole e ricerche restano sul dispositivo. Nessun account, pubblicità o analisi. I download contattano il server, che può ricevere il tuo indirizzo IP.")],
    final_kicker="Per amore dei libri di carta", final_title=("Un bel libro", "ti aspetta."), requirements="Per iPhone · iOS 17 o successivo",
    footer_line="Un po’ più di significato in ogni pagina.", privacy="Privacy", licences="Licenze", credit="Dati lessicali da Wiktionary. Per lettori curiosi.", site_languages="Lingua del sito", related="Altre domande sulla lettura",
)
HOME_UI["de"] = dict(
    nav=("So funktioniert’s", "Sprachen", "Fragen"), get="App laden",
    eyebrow="Ein kleiner Begleiter für gedruckte Bücher", title=("Bleib in", "der", "Geschichte."),
    lead="Ein unbekanntes Wort sollte dich nicht aus einem guten Buch reißen. Richte dein iPhone auf die Seite, finde die Bedeutung und lies weiter.",
    download="Laden im", see="So funktioniert’s", price="Einmaliger Kauf. Kein Abo.",
    photo="Weniger suchen. Mehr lesen.", photo_caption="Das Wörterbuch direkt auf der Seite.", strip="Eine Welt voller Wörter",
    how_kicker="Ein Moment der Neugier", how_title=("Ein Wort.", "Ein bisschen mehr", "Verständnis."),
    how_lead="Kein Tippen, kein App-Wechsel. Ein kurzer Blick und zurück zum Buch.",
    steps=[("Buch und App öffnen.", "Wähle die Sprache deines Buches und tippe auf Lesen starten."),
           ("Auf ein Wort zeigen.", "Halte den kleinen grünen Kreis etwa eine Sekunde über das Wort. Die Markierung bestätigt die Erkennung."),
           ("Bedeutung finden.", "Lies die Definition und wische sie weg. Die Kamera ist sofort für das nächste Wort bereit.")],
    language_kicker="Wähle die Sprache deines Buches", language_title="Sechs Sprachen.",
    language_lead="Englisch ist sofort verfügbar. Lade die anderen Wörterbücher bei Bedarf herunter.",
    built_in="Enthalten", download_pack="Laden", translation="Du liest auf Englisch? Ergänze optionale Übersetzungen in eine der fünf anderen Sprachen.",
    pack_note="Alle Wörterbücher und verfügbaren Übersetzungspakete sind im Kauf enthalten. Installierte Pakete funktionieren offline.",
    screen_caption="Buchsprache in der App.", full_screen="Ganzes Bild ansehen ↗",
    quiet_kicker="Eine unaufdringliche App", quiet_title=("Dein Buch.", "Dein Moment.", "Ganz für dich."),
    benefits=[("Offline lesen.", "Installierte Wörterbücher und Übersetzungen funktionieren ohne Internet."),
              ("Deine Lektüre bleibt privat.", "Kamerabilder und erkannte Wörter bleiben auf deinem iPhone. Ohne Konto, Werbung, Analysen oder Tracking."),
              ("Einmal kaufen.", "Alle sechs Wörterbücher und verfügbaren Übersetzungen sind enthalten. Kein Abo, keine In-App-Käufe.")],
    questions_kicker="Bevor du umblätterst", questions_title=("Ein paar gute", "Fragen."), support="Brauchst du Hilfe? Schreib uns",
    faqs=[("Funktioniert Booktionary offline?", "Ja. Das englische Wörterbuch ist integriert. Lade zusätzliche Wörterbücher und Übersetzungen online herunter; danach funktionieren sie ohne Verbindung. Für den Paketkatalog ist Internet nötig."),
          ("Welche Sprachen kann ich lesen?", "Englisch, Französisch, Spanisch, Portugiesisch, Italienisch und Deutsch. Wähle vor dem Lesen die Buchsprache. Englisch ist integriert; die anderen fünf Wörterbücher werden einzeln geladen."),
          ("Kann die App Wörter übersetzen?", "Für englische Bücher kannst du Übersetzungen in Französisch, Spanisch, Portugiesisch, Italienisch oder Deutsch hinzufügen. Lade zuerst das gewünschte Paket herunter. Die Abdeckung hängt vom Wort ab. Die anderen Sprachen bieten Definitionen ohne Übersetzung."),
          ("Läuft sie auf meinem iPhone?", "Booktionary benötigt ein iPhone mit iOS 17 oder neuer. Gutes Licht hilft bei der Texterkennung."),
          ("Sammelt ihr meine Lesedaten?", "Nein. Bilder, erkannte Wörter und Nachschlagen bleiben auf dem Gerät. Ohne Konto, Werbung oder Analysen. Für Downloads wird der Server kontaktiert, der deine IP-Adresse erhalten kann.")],
    final_kicker="Für die Liebe zu gedruckten Büchern", final_title=("Ein gutes Buch", "wartet auf dich."), requirements="Für iPhone · iOS 17 oder neuer",
    footer_line="Mehr Bedeutung auf jeder Seite.", privacy="Datenschutz", licences="Lizenzen", credit="Wörterbuchdaten aus Wiktionary. Für neugierige Leser.", site_languages="Seitensprache", related="Weitere Fragen zum Lesen",
)
